# Configuration for getting a set of ensemble restarts

# Date range to retrieve ensembles:
datetime_start: 2020-04-07T03:00:00
datetime_final: 2020-05-25T21:00:00
frequency: 6

# Number of random samples from the date range:
number_samples: 15
seed: 1000

# Information about tar files to extract:
tar_files: /archive/u/dao_ops/GEOS-5.25/GEOSadas-5_25/f525_p5_fp/atmens/Y%Y/M%m/f525_p5_fp.atmens_erst.%Y%m%d_%Hz.tar
intenal_files:
  - fvcore_internal_rst
  - moist_internal_rst
  - surf_import_rst
extract_path: /discover/nobackup/drholdaw/JediScratch/StaticB/members/geos
