
# Configuration for running GFS on discover
# -----------------------------------------

jedi_dir: /gpfsm/dnb31/drholdaw/JediDev/fv3-bundle-dev/build-intel-17.0.7.259-release-default
work_dir: /gpfsm/dnb31/drholdaw/JediWF/StaticB/wrk
data_dir: /gpfsm/dnb31/drholdaw/JediWF/fv3-jedi-tools/Data
machine: discover
model: gfs
num_nodes: 6
procs_per_node: 16
job_hours: 1
