# (C) Copyright 2020 UCAR
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.

window_length: 6
type: 4D
timestep: 900

config_files_in:
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/a1_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/a2_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/a3_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/b_parameters_loc_ens.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/b_parameters_loc_fix.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/c_hyb-4dvar_geos.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/d_convert_ana_and_bkg.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/e_analysis_to_increment.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/f_add_increment.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/g_restart_to_background.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/h_hofx.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/i_ensemble_variance.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/cap_restart
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/AGCM.rc
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/Templates/runs.csh

config_files_out:
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/a1_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/a2_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/a3_convert_ensemble.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/b_parameters_loc_ens.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/b_parameters_loc_fix.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/c_hyb-4dvar_geos.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/d_convert_ana_and_bkg.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/e_analysis_to_increment.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/f_add_increment.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/g_restart_to_background.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/h_hofx.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Config/i_ensemble_variance.yaml
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/GeosRunDir/cap_restart
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/GeosRunDir/AGCM.rc
  /gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/runs.csh


# Ensemble
# --------
ensemble_size: 32
ens_sourcepath: '/nfs3m/archive/sfa_cache05/users/g00/drholdaw/f522_c180_dh/atmens/Y%Y/M%m'
ens_targetpath: '/gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Data/Ensemble'
ens_tarfile: 'f522_dh.atmens_erst.%Y%m%d_%Hz.tar'
ens_files:
  - 'f522_dh.fvcore_internal_rst.%Y%m%d_%Hz.nc4'
  - 'f522_dh.moist_internal_rst.%Y%m%d_%Hz.nc4'
  - 'f522_dh.surf_import_rst.%Y%m%d_%Hz.nc4'


# Observations
# ------------
obs_sourcepath: 's3://fv3-jedi/Observations/GFS-16_gsi_diags/'
obs_targetpath: '/gpfsm/dnb31/drholdaw/JediScratch/RealTime4DVarGeos/JediRuns/Data/Observations'
obs_fileformat: 'obs.%Y%m%d%H.tar'
convert_pressures:
  - aircraft_obs_%Y%m%d%H.nc4
  - gps_bend_obs_%Y%m%d%H.nc4
  - rass_tv_obs_%Y%m%d%H.nc4
  - satwind_uv_obs_%Y%m%d%H.nc4
  - scatwind_uv_obs_%Y%m%d%H.nc4
  - sondes_obs_%Y%m%d%H.nc4
  - sfc_obs_%Y%m%d%H.nc4
  - sfcship_obs_%Y%m%d%H.nc4
  - vadwind_uv_obs_%Y%m%d%H.nc4
  - windprof_uv_obs_%Y%m%d%H.nc4
