application:

  application name: parse_file_datetime

  files to parse:
    - ${EXPRDIR}/convertstate_readwrite.yaml
    - ${EXPRDIR}/convertstate_cold2bvars.yaml

  output directory: ${WORKDIR}/${DATETIME}/Config #[./]

  formats to parse:
    - "%y%m%D%H"
    - "%y%m%D_%H"
