untar:

  # Tar command to use [tar]. Can be tar or htar
  tar command: htar

  # Path where to extract tar files [./]
  path to extract to: /scratch1/NCEPDEV/da/Daniel.Holdaway/JediWork/StaticB/EnsembleHolding

  # Tar files to extract
  tar files:
    - '/ESRL/BMC/gsienkf/2year/whitaker/staticBsamples/cube_%Y%m%d%H.tar'

  # Files within the tar files to extract
  internal files:
    - '%Y%m%d%H/mem*/*.nc'
