doinverse: '0'
inputVariables:
  variables: &ivars
  - U
  - V
  - PE
  - PKZ
  - PT
  - Q
  - QILS
  - QICN
  - QLLS
  - QLCN
inputresolution:
  nml_file: Data/fv3files/input.nml
  nml_file_mpp: Data/fv3files/fmsmpp.nml
  pathfile_akbk: Data/fv3files/akbk72.nc4
  trc_file: Data/fv3files/field_table
outputVariables:
  variables:
  - u
  - v
  - ua
  - va
  - t
  - delp
  - ps
  - q
  - qi
  - ql
outputresolution:
  nml_file: Data/fv3files/input.nml
  nml_file_mpp: Data/fv3files/fmsmpp.nml
  pathfile_akbk: Data/fv3files/akbk72.nc4
  trc_file: Data/fv3files/field_table
states:
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem001
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem001
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem002
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem002
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem003
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem003
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem004
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem004
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem005
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem005
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem006
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem006
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem007
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem007
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem008
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem008
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem009
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem009
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem010
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem010
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem011
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem011
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem012
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem012
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem013
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem013
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem014
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem014
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem015
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem015
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem016
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem016
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem017
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem017
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem018
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem018
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem019
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem019
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem020
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem020
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem021
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem021
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem022
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem022
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem023
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem023
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem024
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem024
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem025
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem025
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem026
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem026
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem027
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem027
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem028
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem028
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem029
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem029
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem030
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem030
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem031
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem031
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
- input:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem032
    filename_core: f522_dh.fvcore_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filename_mois: f522_dh.moist_internal_rst.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
    filetype: geos
    variables: *ivars
  output:
    datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem032
    filename_bkgd: geos.bkg.%yyyy%mm%dd_%hhz.nc4
    filetype: geos
varchange: GeosRst2Bkg
