date: '%YWBEG-%mWBEG-%dWBEGT%HWBEG:00:00Z'
variables: ["ua","va","t","ps","q","qi","ql"]
resolution:
  nml_file_mpp: Data/fv3files/fmsmpp.nml
  nml_file: Data/fv3files/input.nml
  trc_file: Data/fv3files/field_table
  pathfile_akbk: Data/fv3files/akbk72.nc4
background:
  filetype: geos
  datapath: Data/Ensemble/f522_dh.atmens_erst.%YWBEG%mWBEG%dWBEG_%HWBEGz/mem001
  filename_bkgd: geos.bkg.%YWBEG%mWBEG%dWBEG_%HWBEGz.nc4
bump:
  prefix: Data/Bump/864_fix/bumpparameters_loc
  verbosity: main
  method: loc
#  nonunit_diag: 1
  strategy: common
  new_nicas: 1
  ntry: 3
  nrep: 2
  lsqrt: 1
  resol: 6
  network: 0
  mpicom: 2
  default_seed: 1
# Forced localization length-scales
# ---------------------------------
  forced_radii: 1
  rh: 2500000.0
  rv: 0.3
# Diagnostic based on ens
# -----------------------
  new_hdiag: 0
  nc1: 2000
  nc2: 500
  nc3: 15
  dc: 200000.0
  nl0r: 11
  ne: 5
  #local_diag: 1
  #local_rad: 1000000
  minim_algo: hooke
  #diag_rhflt: 3000000
#  Dirac gridded output
#  --------------------
  load_nicas: 0
  check_dirac: 0
  ndir: 1
#  londir: [0.0]
#  latdir: [0.0]
#  levdir: [50]
  ivdir: [1]
  itsdir: [1]
  grid_output: 1
  grid_resol: 200000.0
output:
- parameter: loc_coef
  filetype: geos
  datapath: Data/Bump/864_fix
  filename_bkgd: geos.loc_coef.%yyyy%mm%dd_%hh%MM%ssz.nc4
  date: '2019-11-18T09:00:00Z'
- parameter: loc_rh
  filetype: geos
  datapath: Data/Bump/864_fix
  filename_bkgd: geos.loc_rh.%yyyy%mm%dd_%hh%MM%ssz.nc4
  date: '2019-11-18T09:00:00Z'
- parameter: loc_rv
  filetype: geos
  datapath: Data/Bump/864_fix
  filename_bkgd: geos.loc_rv.%yyyy%mm%dd_%hh%MM%ssz.nc4
  date: '2019-11-18T09:00:00Z'
- parameter: hyb_coef
  filetype: geos
  datapath: Data/Bump/864_fix
  filename_bkgd: geos.hyb_coef.%yyyy%mm%dd_%hh%MM%ssz.nc4
  date: '2019-11-18T09:00:00Z'
